- name: EDA Controller | Configure activations
  eda_activations:
    controller_url: "{{ eda_controller_url }}"
    controller_user: "{{ eda_controller_user }}"
    controller_password: "{{ eda_controller_password }}"
    activations: "{{ eda_activations }}"
